#!/usr/bin/env bash
DIR=$(dirname $(realpath "$0"))
SCRIPTS="${DIR}/scripts"

# this is a simple config for herbstluftwm
herbstclient emit_hook reload

# Set default frame layout to horizontal split
herbstclient set default_frame_layout horizontal

# Only set algorithm on first run
if herbstclient silent new_attr bool my_first_autostart false; then
  herbstclient substitute ALGO settings.default_frame_layout \
      foreach T tags.by-name. \
      sprintf ATTR '%c.tiling.root.algorithm' T \
      set_attr ATTR ALGO

  PATH=$PATH:$DIR/scripts
fi

# theme
source "${DIR}/theme.sh"

# Create sessions and tags
herbstclient rename default 1 || true
for key in {2..9} ; do
  herbstclient add $key
done

# rules
herbstclient unrule -F
herbstclient rule focus=on # normally focus new clients
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on --focus=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

herbstclient rule class=FloatMenu  floating=true floating_geometry=1880x880+20+100 floatplacement=center
herbstclient rule class=TopMenu    floating=true floating_geometry=1920x150+0+0
herbstclient rule class=BottomMenu floating=true floating_geometry=1920x150+0+930

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# herbstclient set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# herbstclient detect_monitors

# keybinds
source "${DIR}/keybindings.sh"

# Features
# Focus follow mouse
herbstclient set focus_follows_mouse 1

# Set Wallpaper to my beloved duck image
month=$(date +'%m')
day=$(date +'%d')
if [ $month -ge 11 -a $day -ge 15 ] || [ $month -ge 12 ] || [ $month -le 1 -a $day -le 6 ]
then
    feh --no-fehbg --bg-scale '/home/iago/vault/media/Wallpapers/xmas/duck_xmas.png'
else
    feh --no-fehbg --bg-scale '/home/iago/vault/media/Wallpapers/duck.jpg'
fi

# unlock, just to be sure
herbstclient unlock
