#!/usr/bin/env bash

# this is a simple config for herbstluftwm
herbstclient emit_hook reload

# Set default frame layout to horizontal split
herbstclient set default_frame_layout 1

# theme
source "$HOME/.config/herbstluftwm/theme.sh"

# Create tags
tag_names=( {1..10} )
tag_keys=( {1..9} 0 )

herbstclient rename default "${tag_names[0]}" || true
for tag in "${tag_names[@]}" ; do
    herbstclient add "$tag"
done

# rules
herbstclient unrule -F
#herbstclient rule class=XTerm tag=3 # move all xterms to tag 3
#herbstclient rule focus=off # normally do not focus new clients
# give focus to most common terminals
#herbstclient rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
herbstclient rule focus=on # normally focus new clients
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on --focus=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
herbstclient unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# herbstclient set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# herbstclient detect_monitors

# keybinds
source ~/.config/herbstluftwm/keybindings.sh

# mousebinds
herbstclient mouseunbind --all
herbstclient mousebind Mod4-Button1 move
herbstclient mousebind Mod4-Button2 zoom
herbstclient mousebind Mod4-Button3 resize

# Features
# Focus follow mouse
herbstclient set focus_follows_mouse 1

# Little hack from the FAQ
# Necessary to make vertical splitting the default on tag 1
herbstclient split vertical 0.5 ; herbstclient remove
