#!/bin/sh

LIBRARY="$HOME/Books"
book_ico='📘'

books=$(find $LIBRARY | grep '\.epub\|\.djvu\|\.pdf' | sed "s:${LIBRARY}:${book_ico}:g")
selected=$(echo "$books" | rofi -matching regex -dmenu -i -p "β ")
exit_code=$?

selected="${selected/$book_ico/$LIBRARY}"

if [ $exit_code == 0 ]; then
    zathura "${selected}"
    # xdg-open "${selected}"
    echo $selected
fi
