#!/bin/sh

player_dir="$HOME/.local/share/hists"
player_file="$HOME/.local/share/hists/player"

# List of players to choose from
player_list="$($HOME/.bin/musicctl -l)"

# Get option from list
player="$( echo -e "$player_list" | dmenu -r -i -p '🎶' )"
exit_code="$?"

if [ $exit_code == 0 ]; then
    # Put player name on file to later use
    if ! [ -f "$player_file" ]; then
        mkdir -p "$player_dir" && touch "$player_file"
    fi
    echo $player | tr '[:upper:]' '[:lower:]' > "$player_file"
    herbstclient reload
else
    exit "$exit_code"
fi
