#!/bin/sh

LIBRARY="$HOME/Books"

# Find files with right extensions and remove folder from path
books=$(find $LIBRARY | grep '\.epub\|\.djvu\|\.pdf' | sed "s:${LIBRARY}/::g")
selected=$(echo "$books" | dmenu -l 25 -i -p "β")
exit_code=$?

echo $exit_code
echo "$selected"

if [ $exit_code == 0 ]; then
    echo "Selected book: ${LIBRARY}/$selected"
    zathura "${LIBRARY}/${selected}"
else
    exit "$exit_code"
fi
