#!/bin/sh

term() {
  xterm -e "$1"
}

# List of avaiable options
cfgs="Neovim\nHerbstluftwm\nPulseaudio\nzsh"

choose="$( echo -e "$cfgs" | dmenu -i -l 4 -p '% ' )"

case "${choose}" in
  Neovim)
    term "cd ~/.config/nvim && nvim fnl/startup.fnl" #+':rightbelow 40 vsplit .' +':exe \"normal \<c-w>1\<c-w>\"'"
    ;;
  Herbstluftwm)
    term 'cd ~/.config/herbstluftwm && nvim -O autostart keybindings.sh'
    ;;
 Pulseaudio)
    pavucontrol
    ;;
  zsh)
    term 'cd ~/.zsh.d/ && nvim ~/.zshrc *'
    ;;
esac
