#!/bin/sh

#-------------------------
# Volume
#-------------------------
# Volume information
# Get info from alsa
# and use awk to parse the string inside the first and sixth []
read vol_info vol_ison <<< $(amixer sget Master | awk -F'[][]' 'NF > 1 { print $2, $6 }')

# Check if volume is muted
if [[ "$vol_ison" = 'on' ]]
    then
        vol_symb=🔊
        vol_color='default'
        vol="$vol_symb $vol_info"
    else
        vol_symb=🔇
        vol_color='grey'
        vol="<span color='$vol_color'>$vol_symb $vol_info</span>"
fi

#------------------------
# Battery
#------------------------
batdir=$( echo /sys/class/power_supply/BAT[01])
if [[ -d $batdir ]]
    then
        batlevel=$(cat "$batdir/capacity")%
        batstatus=$(cat "$batdir/status")
    else
        batstatus = "ERROR"
fi
#------------------------
# Screen Brightness
#------------------------
brightness=$(cat /sys/class/backlight/acpi_video1/brightness)
max_brightness=$(cat /sys/class/backlight/acpi_video1/max_brightness)

#------------------------
# Temperature
#------------------------
# Temperature in m°C
temp_symb='🌡'
# Raw temperature in m°C
temp_mC=$(cat /sys/class/thermal/thermal_zone0/temp)
# Formatted temperature
temp_fmt=$( awk '{tp=$1/1000.; printf("%.1f", tp) }' <<<"$temp_mC" )
temp="$temp_symb$temp_fmt°C"

#------------------------
# CPU Status
#------------------------

#-----------------------
# Memory usage
#------------------------
mem_total=$(free -m | grep Mem | awk '{print $2}')
mem_used=$(free -m | grep Mem | awk '{print $3}')
mem_perc=$( awk '{perc=$1/$2*100; printf("%.1f", perc) }' <<<"$mem_used $mem_total" )
mem_perc=${mem_perc}%
#mem_perc=$( free -m | grep Mem | awk '{perc=$2/$3*100; printf("%.1f", perc) }' )

#------------------------
# Date and Time
#------------------------
day=$( date +'%Y.%m.%d')
# date +%w gives the day of the week in {0..6} starting on Sunday
week_day=$(( $(date +%w) + 1 ))
hour=$(date +'%H:%M')

echo "${vol} | ${batlevel} | ${temp} | ${mem_perc} | $brightness/$max_brightness | ${day} [$week_day] | ${hour}"
