#!/bin/sh

#-------------------------
# Volume
#-------------------------
# Check if volume is muted
if [[ $(amixer sget Master | awk -F'[][]' 'NF > 1 { print $6 }') = 'on' ]];
    then vol_status=1
    else vol_status=0
fi

# Volume information
# Get info from alsa
# and use awk to parse the string inside the first []
vol=$(amixer sget Master | awk -F'[][]' 'NF > 1 { print $2 }')

#------------------------
# Battery
#------------------------
batdir=$( echo /sys/class/power_supply/BAT[01])
if [[ -d $batdir ]]
    then
        batlevel=$(cat "$batdir/capacity")
        batstatus=$(cat "$batdir/status")
    else
        batstatus = "ERROR"
fi

#------------------------
# Temperature
#------------------------
# Temperature in m°C
temp_mC=$(cat /sys/class/thermal/thermal_zone0/temp)
temp=$( awk '{tp=$1/1000.; printf("%.1f", tp) }' <<<"$temp_mC" )


#------------------------
# CPU Status
#------------------------

#-----------------------
# Memory usage
#------------------------
mem_total=$(free -m | grep Mem | awk '{print $2}')
mem_used=$(free -m | grep Mem | awk '{print $3}')
mem_perc=$( awk '{perc=$1/$2*100; printf("%.1f", perc) }' <<<"$mem_used $mem_total" )
#mem_perc=$( free -m | grep Mem | awk '{perc=$2/$3*100; printf("%.1f", perc) }' )

#------------------------
# Date and Time
#------------------------
day=$( date +'%Y.%m.%d')
hour=$( date +'%H:%M' )


echo "$vol | ${batlevel}% | ${mem_perc}% | ${temp}°C | $day | $hour"
