#!/bin/bash

# -n : Disable pango markup (no markup)
while getopts n flag; do
    case $flag in
        n)
            nomarkup=true
            ;;
    esac
done
# Remove flag arguments
shift $((OPTIND-1))

# TODO: Tags in another monitors
function beautify_active {
    if [ "$nomarkup" = true ]
    then
        echo "[$1]"
    else
        fg=yellow
        echo "<span font_weight='bold' color='$fg'>$1</span>"
    fi
}
function beautify_urgent {
    if [ "$nomarkup" = true ]
    then
        echo "$1!"
    else
        fg=red
        echo "<span font_weight='heavy' color='$fg'>$1</span>"
    fi
}

# Chinese
declare -A tag_symbol=( \
[1]='一' [2]='二' [3]='三' [4]='四' [5]='五'  \
[6]='六' [7]='七' [8]='八' [9]='九' [10]='十' \
)

# # Tibetan
# declare -A tag_symbol=( \
# [0]=༠ [1]=༡ [2]=༢ [3]=༣ [4]=༤ \
# [5]=༥ [6]=༦ [7]=༧ [8]=༨ [9]=༩ \
# [10]=༡༠                       \
# )

IFS_BAK="${IFS}"
IFS="
"
tag_names=( \
    $(grep -oE '[^][^./(){};:,"#]+|[][^./(){};:,"#]' \
        <<< "$(herbstclient tag_status | sed 's/\t//g')" ) \
)
IFS="${IFS_BAK}"

result=()
flag_empty=false ; flag_used=false ; flag_active=false ; flag_urgent=false

for k in "${tag_names[@]}"; do
    if [ "$k" = '.' ]; then
        flag_empty=true
    elif [ "$k" = ':' ]; then
        flag_used=true
    elif [ "$k" = '#' ]; then
        flag_active=true
    elif [ "$k" = '!' ]; then
        flag_urgent=true
    else
        symbol="${tag_symbol[$k]}"
        if [ $flag_used = true ]; then
            result+=("${symbol}")
        elif [ $flag_active = true ]; then
            result+=("$( beautify_active "${symbol}" )")
        elif [ $flag_urgent = true ]; then
            result+=("$( beautify_urgent "${symbol}" )")
        fi
        # reset flags
        flag_empty=false ; flag_used=false ; flag_active=false
    fi

done

IFS=' ' echo -e "${result[*]}"
