#!/bin/bash

# -p : player to control
# -l : list available players

playfile="$HOME/.local/share/hists/player"

while getopts p:l flag; do
    case $flag in
        p)
            player=${OPTARG}
            ;;
        l)
            echo -e "MPD\nSpotify\nMPV"
            exit 0;
    esac
done

# Remove flag arguments
shift $((OPTIND-1))

if test -z "$player"; then
    player="$(cat "$playfile")"
fi

typeset -A player_cmd
case "${player}" in
    mpd)
        player_cmd[toggle]="mpc -p 6600 toggle"
        player_cmd[play]="mpc -p 6600 play"
        player_cmd[pause]="mpc -p 6600 pause"
        player_cmd[next]="mpc -p 6600 next"
        player_cmd[prev]="mpc -p 6600 prev"
        player_cmd[stop]="mpc -p 6600 stop"
        ;;
    mopidy)
        player_cmd[toggle]="mpc -p 6601 toggle"
        player_cmd[play]="mpc -p 6601 play"
        player_cmd[pause]="mpc -p 6601 pause"
        player_cmd[next]="mpc -p 6601 next"
        player_cmd[prev]="mpc -p 6601 prev"
        player_cmd[stop]="mpc -p 6601 stop"
        ;;
    spotify)
        player_cmd[toggle]="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause"
        player_cmd[play]="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play"
        player_cmd[play]="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause"
        player_cmd[next]="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next"
        player_cmd[prev]="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous"
        player_cmd[stop]="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop"
        ;;
    mpv)
        player_cmd[toggle]="xdotool key --window $(xdotool search --class mpv) p"
        player_cmd[next]="xdotool key --window $(xdotool search --class mpv) greater"
        player_cmd[prev]="xdotool key --window $(xdotool search --class mpv) less"
        player_cmd[stop]="xdotool key --window $(xdotool search --class mpv) q"
        ;;
    *)
        >&2 echo -e "Error: Unkown player '${player}'.\nSupported options are: mpd, mopidy, spotify, mpv."
        exit 1
        ;;
esac

${player_cmd[$1]}
