#!/bin/sh

# -s : argument is script name
# If given, pipes result of script instead of plain text

while getopts s flag; do
    case $flag in
        s)
            sflag=true
            ;;
    esac
done
# Remove flag arguments
shift $((OPTIND-1))

# Remove notifications daemon
pkill dunst

if [[ "$sflag" ]]; then
    notify-send "$($@)"
else
    notify-send "$@"
fi
