#!/bin/bash

print_help() {
echo \
"Usage: notify [flags] [message]
       notify [flags] -e [script_name]

Flag options:
-d : direction of notification on screen
     Avaiable: northeast.
-e : argument is script name. Pipes result instead of text;
-s : Notification summary. Default is 'Notification'."
}

direction='northeast'
summary='Notification'
while getopts ed:s:h flag; do
    case $flag in
        d)
            direction="${OPTARG}"
            ;;
        e)
            exec_flag=true
            ;;
        s)
            summary="${OPTARG}"
            ;;
        h)
            print_help >&2
            ;;
    esac
done
# Remove flag arguments
shift $((OPTIND-1))

if [ "$exec_flag" = true ]; then

    notify-send -c "${direction}" "${summary}" "$($@)"
else
    notify-send -c "${direction}" "${summary}" "$@"
fi
