#!/bin/env zsh

function extract_channel() {
  echo $((16#${1:$2:2}))
}

function int2float() {
  echo $((${1}/256.0))
}

# The color in hexadecimal representation
hex="$(colorpicker --one-shot --short --preview)"

# The color components as Int8 representation
ri=$(extract_channel $hex 1)
gi=$(extract_channel $hex 3)
bi=$(extract_channel $hex 5)

# The color components as floats in [0.0,1.0]
rf=$(int2float $ri)
gf=$(int2float $gi)
bf=$(int2float $bi)

rgb="rgb($ri,$gi,$bi)"

# For glsl
vec3="vec3($rf, $gf, $bf)"

# As used in love2d
love2d="{$rf, $gf, $bf}"

wrapmenu -c cfgmenu \
  "echo -e '$hex\n$rgb\n$vec3\n$love2d' | fzf --border --no-info -1 --height=~40% --prompt='color> ' --layout=reverse | xclip -selection clipboard"
