#!/usr/bin/env zsh
# Sync backup on external hard drive
#
# To dry-run, use -n (only view what will be modified, without really changing it)
# To remove deleted files from backup, use --delete

# Cummulative backup
rsync -avP --copy-links ~/vault/   /media/Elements/vault/
rsync -avP ~/self/    /media/Elements/self/
rsync -avP ~/art/     /media/Elements/art/
rsync -avP ~/code/    /media/Elements/code/
rsync -avP ~/Zotero/  /media/Elements/Zotero/

# Non-cumulative backup

# List of installed packages
yay -Qe > /media/Elements/pacman-installed.txt
