#!/bin/sh
alias locker='slock'

case $1 in
    "lock")
        locker
        ;;
    "suspend")
        locker systemctl suspend -i
        ;;
    "logout")
        herbstclient quit
        ;;
    "hibernate")
        locker systemctl hibernate
        ;;
    "reboot")
        systemctl reboot
        ;;
    "poweroff")
        systemctl poweroff -i
        ;;
    *)
        exit 1
esac
