#!/bin/sh

WIDTH=230
HEIGHT=40
OFFSET_X=0
OFFSET_Y=0

EMULATOR=xterm
TERM_CLASS=wrapmenu

GEOMETRY=$WIDTH"x"$HEIGHT+$OFFSET_X+$OFFSET_Y

while getopts c: flag; do
  case $flag in
    c)
      TERM_CLASS="$OPTARG"
      ;;
  esac
done
shift $((OPTIND-1))


ARGS="$@"

$EMULATOR \
  -class    $TERM_CLASS \
  -geometry $GEOMETRY \
  -e "sh" -c "$ARGS" 2> /dev/null
