#!/bin/sh

finder() {
  fzfmenu -C TopMenu -T 'Config Chooser' \
    --no-info -1 --height=~40% --prompt '% ' --no-multi --layout=reverse \
    --bind 'one:accept'
}

listconfigs() {
  find "${XDG_CONFIG_HOME:-$HOME/.config}" -mindepth 1 -maxdepth 1 -printf "%f\n"
  echo -e "zsh"
  echo -e "pulseaudio"
}

choice="$(listconfigs | finder)"

case "${choice}" in
  nvim)
    herbstclient spawn xterm -e sh -c 'cd ~/.config/nvim && nvim -O fnl/startup.fnl fnl/plugins.fnl'
    ;;
  herbstluftwm)
    herbstclient spawn xterm -e sh -c 'cd ~/.config/herbstluftwm && nvim -O autostart keybindings.sh'
    ;;
  pulseaudio)
    herbstclient spawn pavucontrol
    ;;
  zsh)
    herbstclient spawn xterm -e sh -c 'cd ~/.zsh.d/ && nvim ~/.zshrc *'
    ;;
  *)
    files="$(find "${XDG_CONFIG_HOME:-$HOME/.config}/$choice" -mindepth 1 -maxdepth 1)"
    if [ "$(echo "$files" | wc -l)" -eq 1 ]; then
      herbstclient spawn xterm -e sh -c "cd ${XDG_CONFIG_HOME}/$choice && vi $files"
    else
      herbstclient spawn xterm -e sh -c "cd ${XDG_CONFIG_HOME}/$choice && vi ."
    fi
    ;;
esac
