#!/bin/bash
set -e

function sessionctl() {
  $(dirname "$0")/sessionctl "$@"
}

function hc() {
  herbstclient "$@"
}

function beautify-active() {
  local fg=#f6db55
  echo "<span font_weight='bold' color='$fg'>$1</span>"
}

function beautify-urgent {
  local fg=red
  echo "<span font_weight='heavy' color='$fg'>$1</span>"
}

function beautify_monitor {
  local fg='#62FD52'
  echo "<span font_weight='semibold' color='$fg'>$1</span>"
}

# Chinese
declare -A tag_symbol=( \
[1]='一' [2]='二' [3]='三' [4]='四' [5]='五'  \
[6]='六' [7]='七' [8]='八' [9]='九' [10]='十' \
)

function list-tags() {
  sessionctl query tags
}

function list-tags() {
  sessionctl query tags
}

function prettify() {
  focused=$(hc attr tags.focus.name)

  # Active session name
  printf '<span font_weight="bold" color="%s">%s</span> | ' '#5acc74' "$(sessionctl query active)"

  list-tags | while read -r tag i status; do
    num_clients=$(hc attr tags.by-name.$tag.client_count)
    urgency=$(hc attr tags.by-name.$tag.urgent_count)

    symbol="${tag_symbol[$tag]}"
    if [[ -z $symbol ]]; then
      symbol=$tag
    fi

    printf "${tag_symbol[$i]}:"

    if   [[ $tag = $focused ]]; then
      echo "$( beautify-active "${symbol}" )"
    elif [[ $urgency -gt 0 ]]; then
      echo "$( beautify-urgent "${symbol}" )"
    elif [[ $status = active ]]; then
      echo "$( beautify-monitor "${symbol}" )"
    else
      echo "${symbol}"
    fi
  done

}

notify-send -h string:x-dunst-stack-tag:tags "tag-list" "$(prettify | tr '\n' ' ')"
