#!/bin/bash

function sessionctl() {
  $(dirname $(realpath "$0"))/sessionctl $@
}
#

function session-finder() {
  fzfmenu -C FloatMenu -T 'Session Switcher' \
    --border --prompt='=> ' --info=inline \
    --header=$'~:~ Session Selection ~:~' \
    --cycle \
    --header-lines=1 \
    --preview="sessionctl query tags {2}" \
    --select-1 \
    --bind 'one:accept' \
    --expect='alt-Q,alt-t'
}

function tag-finder() {
  fzfmenu -C FloatMenu -T 'Tag Switcher' \
    --border --prompt='=> ' --info=inline \
    --header=$'~:~ Tag Selection ~:~' \
    --cycle --multi --nth=1 \
    --bind 'one:accept' \
    --expect='alt-Q,alt-bspace'
}

function list-tags() {
  herbstclient foreach T tags.by-name \
                 sprintf S  "%{%c.name} (%{%c.client_count})" T T \
                 echo S | column -t | sort -n -k 1
}

function list-sessions() {
  echo "M-Q : kill session | M-t : send to session"
  sessionctl query all | while read -r session index status; do
    echo $index $session $active
  done | column -t
}

function focused-tag() {
  herbstclient get_attr tags.focus.name
}

if [[ "$1" = sessions ]]; then
  mapfile -t out <<<"$(list-sessions | session-finder)"

  key="${out[0]}"
  sessions=$(printf "%s\n" "${out[@]:1}" | awk '{print $2}')

  case "$key" in
    alt-Q)      # Kill session
      sessionctl kill $sessions
      ;;
    alt-t)      # Remove tags from session
      my_tag=$(focused-tag)

      for session in $sessions; do
        sessionctl add-tag $session $my_tag
      done
      ;;
    *)          # Go to session
      sessionctl enter "$( echo $sessions | tail -1)"
  esac
else
  mapfile -t out <<<"$(list-tags | tag-finder)"

  key="${out[0]}"
  tags=$(printf "%s\n" "${out[@]:1}" | cut -d' ' -f1)

  case "$key" in
    alt-Q)      # Remove tags from session
      my_session=$(herbstclient get_attr my_session)
      for tag in $tags; do
        sessionctl rm-tag $my_session $tag
      done
      ;;
    alt-bspace) # Merge tags with current tag
      for tag in $tags; do
        herbstclient merge_tag $tag
      done
      ;;
    *)          # Go to tag
      herbstclient use "$( echo $tags | tail -1)"
  esac
fi
