#!/bin/bash

function sessionctl() {
  $(dirname $(realpath "$0"))/sessionctl $@
}
#

function session-finder() {
  fzf --border --prompt='=> ' --info=inline \
      --header=$'~:~ Session Selection ~:~' \
      --cycle --nth=1 \
      --header-lines=1 \
      --expect='alt-t'
}

function tag-finder() {
  fzf --border --prompt='=> ' --info=inline \
      --header=$'~:~ Session Selection ~:~' \
      --cycle --multi --nth=1 \
      --expect='alt-Q,alt-bspace'
}

function list-tags() {
  herbstclient foreach T tags.by-name \
                 sprintf S  "%{%c.name} (%{%c.client_count})" T T \
                 echo S | column -t | sort -n -k 1
}

function list-sessions() {
  echo "M-t : send to session"
  sessionctl query all
}

function focused-tag() {
  herbstclient get_attr tags.focus.name
}

if [[ "$1" = sessions ]]; then
  mapfile -t out <<<"$(list-sessions | session-finder)"

  key="${out[0]}"
  sessions=$(printf "%s\n" "${out[@]:1}" | cut -d' ' -f1)

  case "$key" in
    alt-t)      # Remove tags from session
      my_tag=$(focused-tag)

      for session in $sessions; do
        herbstclient emit_hook session_tag_add $session $my_tag
      done
      ;;
    *)          # Go to session
      herbstclient emit_hook session_enter "$( echo $sessions | tail -1)"
  esac
else
  mapfile -t out <<<"$(list-tags | tag-finder)"

  key="${out[0]}"
  tags=$(printf "%s\n" "${out[@]:1}" | cut -d' ' -f1)

  case "$key" in
    alt-Q)      # Remove tags from session
      my_session=$(herbstclient get_attr my_session)
      for tag in $tags; do
        sessionctl rm-tag $my_session $tag
      done
      ;;
    alt-bspace) # Merge tags with current tag
      for tag in $tags; do
        herbstclient merge_tag $tag
      done
      ;;
    *)          # Go to tag
      herbstclient use "$( echo $tags | tail -1)"
  esac
fi
